### ISSUE TITLE
Duplicate messages

### ISSUE THREAD

**Issue by artema** [TopCloud/sc-redis#1]
Whenever I send a message, it arrives twice. From what I saw, this might not be a bug of this particular store implementation, but the SC store system. Am I missing something here?

**Comment by jondubois** [comment]
I haven't encountered this problem before.

How many store processes are you using when running SC?
Where are you publishing the message from? From the client or server?

**Comment by jondubois** [comment]
Also, when you say that the message 'arrives twice' - Do you mean the client (browser) receives it twice?

**Comment by artema** [comment]
I have a single store process. The message comes from a client that is subscribed to the receiving channel, from which the message comes twice in a row. It only happens when I use this store.

**Comment by killingz0e** [comment]
That also happens to me: channel.watch always give me back 2 duplicated messages. 

I checked with redis monitor, I checked on the server, and the message is correctly pushed (1 time).

**Comment by jondubois** [comment]
@killingz0e I will look into this.

**Comment by jondubois** [comment]
@killingz0e @artema Ok, this has been fixed, it was in fact an issue with sc-redis (not SocketCluster). That said, I did make a change to both SC1 and SC2 to attach a UUID 'instanceId' to each store process automatically (as an alternative to providing one as a storeOption). All stores and workers in a single SC instance share the same instanceId.

You should update to the latest version of socketcluster/sc2 (remember to do npm cache clean if you run into any issues). Also you need to get the latest version of sc-redis.

This issue occurred because your SC stores would automatically process messages internally (as normal) but because stores were also subscribed to the channel on the remote Redis server, it would get its own message back and process it again (not considering the fact that this message came from its own instance and was therefore already handled).

Now the store will ignore messages which where sent by itself (or a sibling store which belongs to the same local SC instance/cluster of processes).

I don't think Redis supports a 'do not publish message back to publisher' feature, so we'll have to do with the 'filter out' approach.

Note that while sc-redis does work, it is not a complete solution. At this stage, its main purpose is to demonstrate how to scale SC horizontally. Though it may be suitable in some (non-critical) scenarios in production.

The two main issues with it:
- It is not password protected (although, you should be able to tweak sc-redis to make use of a password from store.options) - The store.options object comes from storeOptions here: http://socketcluster.io/#!/docs/api-socketcluster
- It is not particularly good at handling Redis server crashes or lost connections - It will crash your store processes if the connection fails (although, thankfully they will keep respawning until the connection is regained so it will only cause temporary disruptions with your pub/sub).

I would like to fix the first issue when I get the time, but if someone else can submit a pull request, that would be great. The code for sc-redis is quite simple once you understand the big picture of how it relays messages between Redis and your SC instance.
