### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by bencevans** [TopCloud/sc-redis#4]
Hi,

Have you looked into testing the stores when written as a separate project from the app?

Cheers,

Ben

**Comment by jondubois** [comment]
Stores are nData instances (https://github.com/socketcluster/ndata) - Test coverage for nData is over 70%.

Have you found any issues?

**Comment by bencevans** [comment]
Haven't found any issues per se but have written a project very similar to this one connecting SocketCluster to NSQ and wondered if there were any examples of testing store implementations such as this one. However there doesn't appear to be any testing on this project yet.

**Comment by jondubois** [comment]
I see - So that way you could just use the same tests to validate that your stores are synchronizing regardless of your specific implementation.

That's a good idea - I should do this eventually. I have a lot of stuff to do though so if you end up writing your own tests (based on your NSQ implementation) and they're generic enough to apply to other transport layers like Redis, then a pull request would be appreciated :p

Surprisingly, I hadn't heard of NSQ before but it looks really good. I should try it out.

**Comment by bencevans** [comment]
Written a few tests on https://github.com/webcast-io/sc-redis-outbound feel free to take them :smile:

Also you mention in the README that you want Authentication. Do you mean authenticating to Redis? As the `redis` module automatically provides this by giving storeOptions a `auth_pass` value.

**Comment by jondubois** [comment]
@bencevans I just checked the Redis docs again - You're right, I must have missed this. I'll update the README :)

**Comment by jondubois** [comment]
@bencevans I'll try to merge your fork this weekend sometime.

**Comment by bencevans** [comment]
Awesome :)

@bencevans https://github.com/bencevans I'll try to merge your fork this
weekend sometime.

**Comment by jondubois** [comment]
Closing this. I was only able to get one commit from that fork since it diverges a bit.
